[libraries]
junit = { group = "junit", name = "junit", version = "4.13.2" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version = "1.3.0" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version = "2.11.0" }
changelog = { id = "org.jetbrains.changelog", version = "2.5.0" }
